<?php include 'layout.head.phtml'; ?>
<div id="main-body"><?php include $data['view'] . '.phtml'; ?></div>
<div id="signature">
  <a href="https://www.linkedin.com/in/golotiuk/" target="_blank" rel="nofollow">Denys Golotiuk</a>
  in <?=date('Y')?>

  <p>I'm a database architect, focused on OLAP databases
  for storing & processing large amounts of data in an efficient manner.
  Let me know if you have questions or need help.</p>

  Contact me via <a href="mailto:golotyuk@gmail.com">golotyuk@gmail.com</a> or 
  <a href="https://github.com/mrcrypster">mrcrypster @ github</a>
</div>
