<head>
  <title><?=$this->title($data)?></title>

  <link rel="stylesheet" href="/s.css">
  <link rel="icon" type="image/png" href="/i/child-128.png" />

  <script src="https://cdnjs.cloudflare.com/ajax/libs/leader-line/1.0.7/leader-line.min.js" integrity="sha512-0dNdzMjpT6pJdFGF1DwybFCfm3K/lzHhxaMXC/92J9/DZujHlqYFqmhTOAoD0o+LkeEsVK2ar/ESs7/Q2B6wJg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="/s.js"></script>
</head>
