<head>
  <title><?=$this->title($data)?></title>
  <?php if ( isset($data['article']) ) { ?>
    <meta name="description" content="<?=htmlspecialchars($data['article']['description'])?>">
    <link rel="canonical" href="https://datachild.net<?=$data['article']['url']?>"/>
  <?php } else if ( isset($data['category']) ) { ?>
    <meta name="description" content="Articles about <?=htmlspecialchars($data['category'])?>">
    <link rel="canonical" href="https://datachild.net<?=$data['category']?>"/>
  <?php } else { ?>
    <link rel="canonical" href="https://datachild.net/"/>
  <?php } ?>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="/s.css?3">
  <link rel="icon" type="image/png" href="/i/child-128.png" />

  <script defer src="https://cdnjs.cloudflare.com/ajax/libs/leader-line/1.0.7/leader-line.min.js" integrity="sha512-0dNdzMjpT6pJdFGF1DwybFCfm3K/lzHhxaMXC/92J9/DZujHlqYFqmhTOAoD0o+LkeEsVK2ar/ESs7/Q2B6wJg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script defer src="/s.js?1"></script>
</head>
