<article>
  <h1><?=htmlspecialchars($data['article']['title'])?></h1>

  <?=$data['article']['html']?>

  <small>
    Published
    <?=published($data['article']['publish'])?>
    in #<a href="/<?=$data['article']['category']?>"><b><?=$data['article']['category']?></b></a>
    <?=tags($data['article']['tags'], true)?><br/>
    <a href="https://github.com/mrcrypster/datachild/articles/<?=parse_url($data['article']['url'])['path']?>.md">Edit on Github</a>
  </small>
</article>
